### ISSUE TITLE
Additional Collision Models

### ISSUE THREAD

**Issue by jcoll44** [erwincoumans/tiny-differentiable-simulator#10]
Hi,
Looking at the collision models available with TDS only planes, spheres and capsules are implemented. Cubes and meshes are currently unavailable. Is there a plan for more collision models to be supported and if so is there a timeline for this?

**Comment by erwincoumans** [comment]
Maybe, but there are no plans or timelines for the tiny-differentiable-simulator at the moment. So closing for now, if there is a plan/effort we re-open.

**Comment by gonultasbu** [comment]
Does the repository have the mesh collision implemented as of now?
