### ISSUE TITLE
Fail to make

### ISSUE THREAD

**Issue by Cospui** [erwincoumans/tiny-differentiable-simulator#16]
By following the instructions in the "Getting Started" part, I got the following error when running `make -j` (after `mkdir build`,`cd build`, `cmake ..`):

`make *** no targets specified and no makefile found. stop`

So how can I solve this? Thanks!

**Comment by erwincoumans** [comment]
It works fine on all platforms for me (WIndows, Linux, Mac OSX). More details needed, what OS + version, what version of cmake etc.

**Comment by erwincoumans** [comment]
Can't reproduce.

**Comment by gonultasbu** [comment]
Mentioned problem can be solved by modifying the cmake command as follows:

`cmake -G "Unix Makefiles" ..`
