### ISSUE TITLE
Example run issue

### ISSUE THREAD

**Issue by RupaliArtpark** [erwincoumans/tiny-differentiable-simulator#176]
I followed following commands :
$ git clone https://github.com/google-research/tiny-differentiable-simulator.git
$ cd tiny-differentiable-simulator
$ mkdir build
$ cd build 
$ cmake ..
$ make -j

cmake and make-j was successful.

After executing these commands I went ahead to test the example scripts
$ cd tiny-differentiable-simulator/examples
$ g++ tiny_urdf_parser_meshcat_example.cpp

errors are popping up.  
fatal error: cpp_base64/base64.h: No such file or directory
   20 | #include <cpp_base64/base64.h>
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
cpp_base64/base64.h is present in build directory. So I tried providing compiler path to build and later src but again guid.hpp is not found. guid.hpp is not present inside crossguid
fatal error: crossguid/guid.hpp: No such file or directory
   19 | #include <crossguid/guid.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.

I tried $g++ -I/path/to/tiny-directory/build  tiny_urdf_parser_meshcat_example.cpp

I tried $g++ -I/path/to/tiny-directory/src tiny_urdf_parser_meshcat_example.cpp

Please help to get the examples running.

**Comment by erwincoumans** [comment]
cmake and make -j should already have build various examples. You cannot build a separate cpp file, a build system is more complicated than that.
So after running make -j try

```
./examples/spherical_joint_test_eigen
```
