### ISSUE TITLE
Issue during initial install

### ISSUE THREAD

**Issue by BPDanek** [erwincoumans/tiny-differentiable-simulator#19]
When trying to install the `make -j` step returns

Rerunning does the same.
```
[ 22%] Built target pytinydiffsim
[ 26%] Built target opengl_imgui_test
[ 28%] Built target pendulum_example_gui
[ 31%] Built target tiny_urdf_parser_opengl_example
[ 35%] Built target opengl_test
[ 36%] Built target pytinyopengl3
[ 98%] Built target zmq
make: *** [all] Error 2
```

I am using GCC and G++ 10, same bug comes up with GCC and G++ 7.
Ran on MacOS and Ubuntu 16

**Comment by BPDanek** [comment]
It looks like there were issues during build too, got an error similar to: https://github.com/ros-planning/navigation/issues/617
resolved with: https://github.com/ros-planning/navigation/issues/617#issuecomment-391005166

**Comment by BPDanek** [comment]
It looks like there were issues during build too, got an error similar to: https://github.com/ros-planning/navigation/issues/617
resolved with: https://github.com/ros-planning/navigation/issues/617#issuecomment-391005166

**Comment by erwincoumans** [comment]
Can't reproduce, it compiles/build, links and runs on Windows, Linux and Mac OSX, if you follow the required dependencies etc.
