### ISSUE TITLE
Adding friction property

### ISSUE THREAD

**Issue by mikel-zhobro** [erwincoumans/tiny-differentiable-simulator#198]
Combining the friction requires the friction_coefs of the two bodies in contact.
Since contacts are computed between geometries, I suggest a `friction` property should be added to the `Geometry` class.

To keep it compatible, we can add a `friction` property on `RigidBody` and` MultiBody` also. 

The idea is to go one level above if `friction` is not defined, i.e.  Geometry -> Rigid-/MultiBody -> World. 
A negative coefficient can indicate that the property is not defined.

I can go ahead and implement this if I get approval.

 (edit 1)
**Just as a side note,** my motivation is to perform **system identification** on the friction coefficients.

Related to :
https://github.com/erwincoumans/tiny-differentiable-simulator/blob/c1a9e06de33756bceacfaddeecc6bc4b6c98560c/src/world.hpp#L186-L190
and
https://github.com/erwincoumans/tiny-differentiable-simulator/blob/c1a9e06de33756bceacfaddeecc6bc4b6c98560c/src/world.hpp#L266-L270

**Comment by erwincoumans** [comment]
If this is useful to you, it is probably best if you just implement this in a fork.
