### ISSUE TITLE
Get Coriolis matrix

### ISSUE THREAD

**Issue by ad1t7a** [erwincoumans/tiny-differentiable-simulator#22]
Is there a way to get the coriolis matrix using this approach? I realize that we can get the "C(q, qdot) * qdot" term using the inverse dynamics function, but is there a way to isolate just the C(q, qdot) matrix?

**Comment by erwincoumans** [comment]
It is not implemented yet.

**Comment by ad1t7a** [comment]
Thanks for the update!
