### ISSUE TITLE
libasound2-dev is a requirement to compile

### ISSUE THREAD

**Issue by thvhauwe** [erwincoumans/tiny-differentiable-simulator#55]
Compiling with `make -j` resulted in `fatal error: alsa/asoundlib.h: No such file or directory` without install of deb pkg `libasound2-dev`. Error can be resolved with a simple `sudo apt install libasound2-dev` on ubuntu focal fossa.

**Comment by erwincoumans** [comment]
Good point, we can make it optional and add a hint of sudo apt install libasound2-dev in build_libs_unix.sh

**Comment by erwincoumans** [comment]
removed the need for the dependency.
