### ISSUE TITLE
Missing lBulletRoboticsGUI and lBulletDynamics

### ISSUE THREAD

**Issue by mfogelson** [erwincoumans/tiny-differentiable-simulator#77]
OS: MacOS Catalina

I did a homebrew install of Bullet:
<img width="565" alt="Screen Shot 2021-02-09 at 8 46 04 PM" src="https://user-images.githubusercontent.com/23368739/107452783-d6607e80-6b17-11eb-8372-6d88451aa025.png">

I did a python3 install of pybullet:
<img width="924" alt="Screen Shot 2021-02-09 at 8 48 01 PM" src="https://user-images.githubusercontent.com/23368739/107452980-1cb5dd80-6b18-11eb-8e4a-05f7113ce6d9.png">
 
Now I am trying to build tiny-differntiable-simulator but getting the following clang error: 
<img width="577" alt="Screen Shot 2021-02-09 at 8 43 05 PM" src="https://user-images.githubusercontent.com/23368739/107452561-6baf4300-6b17-11eb-9b1c-a0fc396f66ab.png">

However, when I look into the brew install of bullet I see those libraries there. 

I thought that this issue: https://github.com/bulletphysics/bullet3/issues/2758 might address my problem but I dont see where to add the 
```TARGET_LINK_LIBRARIES(<YOUR_APP> BulletRoboticsGUI BulletExampleBrowserLib BulletRobotics BulletFileLoader BulletWorldImporter BulletSoftBody BulletDynamics BulletCollision BulletInverseDynamicsUtils BulletInverseDynamics LinearMath OpenGLWindow gwen BussIK Bullet3Common)```

**Comment by erwincoumans** [comment]
We'll remove the Bullet dependency in the future, for now, try to comment-out the find_package(bullet) in the cmakelists.txt file.
